# Generated by Django 4.0.2 on 2022-05-21 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(blank=True, max_length=100)),
                ('movie_genre', models.CharField(blank=True, max_length=100)),
                ('overall_rating', models.IntegerField(blank=True, default=None, null=True)),
                ('date_release', models.DateField(blank=True, default=None, null=True)),
                ('movie_image_url', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrizeList',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('require_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reward_Point',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point', models.IntegerField(blank=True, default=None, null=True)),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('code', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('redeem_item_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.prizelist')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RatingList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_id', models.IntegerField(blank=True, default=None, null=True)),
                ('date_rating', models.DateField(auto_now_add=True)),
                ('rating_score', models.IntegerField(blank=True, default=None, null=True)),
                ('action', models.CharField(blank=True, choices=[('Rate', 'Rate'), ('Share', 'Share')], default=None, max_length=20, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interact_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(blank=True, default=None, null=True)),
                ('movie_name', models.CharField(blank=True, max_length=100)),
                ('movie_image_url', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CF_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weighted_score', models.IntegerField(blank=True, default=None, null=True)),
                ('movie_id', models.IntegerField(blank=True, default=None, null=True)),
                ('movie_name', models.CharField(blank=True, max_length=100)),
                ('movie_image_url', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
