# Generated by Django 4.0.2 on 2022-02-12 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_todolist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(choices=[('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Action', 'Action'), ('Drama', 'Drama'), ('Crime', 'Crime'), ('Children', 'Children'), ('Mystery', 'Mystery'), ('Documentary', 'Documentary'), ('Animation', 'Animation'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Western', 'Western'), ('Film-Noir', 'Film-Noir'), ('Romance', 'Romance'), ('War', 'War'), ('Sci-Fi', 'Sci-Fi'), ('Musical', 'Musical')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
