# Generated by Django 4.0.2 on 2022-02-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
