# Generated by Django 4.0.2 on 2022-02-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=60, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email address')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=60, unique=True, verbose_name='firstname')),
                ('last_name', models.CharField(max_length=60, unique=True, verbose_name='lastname')),
                ('cc_number', models.CharField(max_length=60, unique=True, verbose_name='cc_number')),
                ('cc_name', models.CharField(max_length=60, unique=True, verbose_name='cc_name')),
                ('cc_expirydate', models.CharField(max_length=60, unique=True, verbose_name='cc_expirydate')),
                ('cc_cvv', models.CharField(max_length=60, unique=True, verbose_name='cc_cvv')),
                ('genres', models.CharField(choices=[('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Action', 'Action'), ('Drama', 'Drama'), ('Crime', 'Crime'), ('Children', 'Children'), ('Mystery', 'Mystery'), ('Documentary', 'Documentary'), ('Animation', 'Animation'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Western', 'Western'), ('Film-Noir', 'Film-Noir'), ('Romance', 'Romance'), ('War', 'War'), ('Sci-Fi', 'Sci-Fi'), ('Musical', 'Musical')], max_length=30)),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
