# Generated by Django 4.0.2 on 2022-02-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
