# Generated by Django 4.0.2 on 2022-03-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100)),
                ('overall_rating', models.IntegerField()),
                ('date_release', models.DateField()),
                ('movie_image_url', models.CharField(max_length=255)),
            ],
        ),
    ]
