# Generated by Django 4.0.2 on 2022-03-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_movielist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
        migrations.AddField(
            model_name='movielist',
            name='movie_genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='date_release',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='movie_image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='movie_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='overall_rating',
            field=models.IntegerField(blank=True),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
