# Generated by Django 4.0.2 on 2022-03-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_todolist_user_movielist_movie_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='date_release',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
