# Generated by Django 4.0.2 on 2022-03-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_movielist_movie_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('date_rating', models.DateField(blank=True, default=None, null=True)),
                ('rating_score', models.IntegerField(blank=True, default=None, null=True)),
                ('movie_id', models.IntegerField(blank=True, default=None, null=True)),
                ('action', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
