# Generated by Django 4.0.2 on 2022-03-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_ratinglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeList',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('require_points', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ratinglist',
            name='username',
        ),
        migrations.AddField(
            model_name='ratinglist',
            name='user_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ratinglist',
            name='action',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
