# Generated by Django 4.0.2 on 2022-03-13 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_alter_ratinglist_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratinglist',
            name='action',
            field=models.CharField(blank=True, choices=[('Rate', 'Rate'), ('Share', 'Share')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ratinglist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ratinglist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
