# Generated by Django 4.0.2 on 2022-03-17 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_alter_ratinglist_action_alter_ratinglist_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward_Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(blank=True, default=None, null=True)),
                ('date_modified', models.DateField(blank=True, default=None, null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
