# Generated by Django 4.0.2 on 2022-03-17 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_reward_point_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reward_point',
            options={},
        ),
    ]
