# Generated by Django 4.0.2 on 2022-03-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_reward_point_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratinglist',
            name='date_rating',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reward_point',
            name='date_modified',
            field=models.DateField(auto_now_add=True),
        ),
    ]
