# Generated by Django 4.0.2 on 2022-03-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_ratinglist_date_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizelist',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
