# Generated by Django 4.0.2 on 2022-03-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_reward_point_redeem_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward_point',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
