# Generated by Django 4.0.2 on 2022-03-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_reward_point_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward_point',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
