# Generated by Django 4.0.2 on 2022-03-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_reward_point_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward_point',
            name='date_modified',
            field=models.DateField(auto_now_add=True),
        ),
    ]
