# Generated by Django 4.0.2 on 2022-03-20 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
