# Generated by Django 4.0.2 on 2022-04-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_cf_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='cf_list',
            name='movie_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
