# Generated by Django 4.0.2 on 2022-04-17 03:27

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_cf_list_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward_point',
            name='redeem_item_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=main.models.PrizeList),
        ),
    ]
