# Generated by Django 4.0.2 on 2022-04-19 13:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0037_cfview_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CFView_List',
            new_name='Interact_List',
        ),
    ]
