# Generated by Django 4.0.2 on 2022-03-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_creditcard_cc_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cc_expirydate',
            field=models.CharField(max_length=40, unique=True, verbose_name='cc_expirydate'),
        ),
    ]
