# Generated by Django 4.0.2 on 2022-03-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_alter_creditcard_cc_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cc_cvv',
            field=models.CharField(max_length=3, verbose_name='cc_cvv'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cc_expirydate',
            field=models.CharField(max_length=4, verbose_name='cc_expirydate'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cc_name',
            field=models.CharField(max_length=40, verbose_name='cc_name'),
        ),
    ]
