# Generated by Django 4.0.2 on 2022-03-19 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_alter_creditcard_cc_cvv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='subscription_enddate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 17, 57, 58, 921097)),
        ),
    ]
