# Generated by Django 4.0.2 on 2022-03-19 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_creditcard_subscription_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='subscription_enddate',
            field=models.DateField(default=datetime.datetime(2022, 4, 18, 17, 58, 37, 24556)),
        ),
    ]
