# Generated by Django 4.0.2 on 2022-03-26 12:46

import creditcards.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0029_alter_creditcard_subscription_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cc_cvv',
            field=creditcards.models.SecurityCodeField(max_length=4, verbose_name='security code'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cc_expirydate',
            field=creditcards.models.CardExpiryField(verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cc_number',
            field=creditcards.models.CardNumberField(max_length=25, verbose_name='card number'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='subscription_enddate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 12, 46, 45, 581636, tzinfo=utc)),
        ),
    ]
