# Generated by Django 4.0.2 on 2022-04-19 13:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0037_alter_bankin_subscription_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankin',
            name='subscription_enddate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 13, 10, 11, 720924, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='subscription_enddate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 13, 10, 11, 719919, tzinfo=utc)),
        ),
    ]
